extend type Mutation {
    """
    Create a new user and automatically initialize customer account
    """
    createUser(
        name: String!
        email: String!
        password: String!
        cartId: ID @globalId(decode: ID)
    ): LoginResponse
    @field(resolver: "Lunargraphql\\GraphQL\\Resolvers\\UserResolver@createUser")
    @throttle(
        maxAttempts: 10
        decayMinutes: 1
    )

    """
    Login a user and optionally merge/associate guest cart
    """
    login(
        email: String!
        password: String!
        cartId: ID @globalId(decode: ID)
    ): LoginResponse
    @field(resolver: "Lunargraphql\\GraphQL\\Resolvers\\UserResolver@login")
    @throttle(
        maxAttempts: 10
        decayMinutes: 1
    )

    """
    Logout a user and revoke current access token
    """
    logout: Boolean
    @guard
    @field(resolver: "Lunargraphql\\GraphQL\\Resolvers\\UserResolver@logout")

    """
    Reset password for currently authenticated user
    """
    resetPassword(
        currentPassword: String
        password: String!
        passwordConfirmation: String
    ): Boolean
    @guard
    @field(resolver: "Lunargraphql\\GraphQL\\Resolvers\\UserResolver@resetPassword")
    @throttle(
        maxAttempts: 10
        decayMinutes: 10
    )

    """
    Send reset password email
    """
    sendResetPasswordEmail(
        email: String!
    ): Boolean
    @field(resolver: "Lunargraphql\\GraphQL\\Resolvers\\UserResolver@sendResetPasswordEmail")
    @throttle(
        maxAttempts: 10
        decayMinutes: 10
    )

    """
    Reset password using email token
    """
    sendResetPasswordFromToken(
        token: String!
        email: String!
        password: String!
        passwordConfirmation: String
    ): Boolean
    @field(resolver: "Lunargraphql\\GraphQL\\Resolvers\\UserResolver@resetPasswordFromToken")
    @throttle(
        maxAttempts: 10
        decayMinutes: 10
    )
}

extend type Query {
    """
    The currently authenticated user
    """
    me: User!
    @guard
    @field(resolver: "Lunargraphql\\GraphQL\\Resolvers\\UserResolver@me")
}
