extend type Mutation {
    """
    Create a new user and associate with customer if provided
    """
    createUser(
        name: String!
        email: String!
        password: String!
        customerID: ID @globalId(decode: ID)
    ): LoginResponse
    @field(resolver: "Lunargraphql\\GraphQL\\Resolvers\\UserResolver@createUser")

    """
    Login a user
    """
    login(
        email: String!
        password: String!
    ): LoginResponse
    @field(resolver: "Lunargraphql\\GraphQL\\Resolvers\\UserResolver@login")

    """
    Logout a user and revoke tokens
    """
    logout: Boolean
    @guard
    @field(resolver: "Lunargraphql\\GraphQL\\Resolvers\\UserResolver@logout")

    """
    Reset password for currently authenticated user
    """
    resetPassword(
        password: String!
    ): Boolean
    @guard
    @field(resolver: "Lunargraphql\\GraphQL\\Resolvers\\UserResolver@resetPassword")
    @throttle(
        maxAttempts: 10
        decayMinutes: 10
    )

    """
    Send reset password email
    """
    sendResetPasswordEmail(
        email: String!
    ): Boolean
    @field(resolver: "Lunargraphql\\GraphQL\\Resolvers\\UserResolver@sendResetPasswordEmail")
    @throttle(
        maxAttempts: 10
        decayMinutes: 10
    )

    """
    Reset password using email token
    """
    sendResetPasswordFromToken(
        token: String!
        email: String!
        password: String!
        passwordConfirmation: String
    ): Boolean
    @field(resolver: "Lunargraphql\\GraphQL\\Resolvers\\UserResolver@resetPasswordFromToken")
}

extend type Query {
    """
    The currently authenticated user
    """
    me: User!
    @guard
    @field(resolver: "Lunargraphql\\GraphQL\\Resolvers\\UserResolver@me")
}
