extend type Query {
    """
    Get the current session cart or create a new one
    """
    getCart: Cart!
    @field(resolver: "Lunargraphql\\GraphQL\\Resolvers\\CartResolver@getCartQuery")

    """
    Get available shipping options for the current cart
    """
    shippingOptions: [ShippingOption!]!
    @field(resolver: "Lunargraphql\\GraphQL\\Resolvers\\CartResolver@getShippingOptionsQuery")

    """
    Get estimated shipping options for arbitrary destination before full address entry
    """
    estimateShipping(
        countryId: ID
        country: String
        state: String
        postcode: String
    ): [ShippingOption!]!
    @field(resolver: "Lunargraphql\\GraphQL\\Resolvers\\CartResolver@estimateShippingQuery")
}

extend type Mutation {
    """
    Change the currency of the current cart
    """
    setCartCurrency(
        currencyCode: String!
    ): Cart!
    @field(resolver: "Lunargraphql\\GraphQL\\Resolvers\\CartResolver@setCartCurrencyMutation")
    """
    Add or update a product variant in the cart
    """
    addProductVariantToCart(
        productVariantID: ID!
        quantity: Int = 1
        meta: String
    ): Cart!
    @field(resolver: "Lunargraphql\\GraphQL\\Resolvers\\CartResolver@addProductVariantToCartMutation")

    """
    Update a specific line in the cart
    """
    updateCartLine(
        cartLineID: ID!
        quantity: Int!
        meta: String
    ): Cart!
    @field(resolver: "Lunargraphql\\GraphQL\\Resolvers\\CartResolver@updateCartLineMutation")

    """
    Remove a specific line from the cart
    """
    removeCartLine(
        cartLineID: ID!
    ): Cart!
    @field(resolver: "Lunargraphql\\GraphQL\\Resolvers\\CartResolver@removeCartLineMutation")

    """
    Clear all items from the cart
    """
    clearCart: Cart!
    @field(resolver: "Lunargraphql\\GraphQL\\Resolvers\\CartResolver@clearCartMutation")

    """
    Set shipping address on the cart
    """
    setCartShippingAddress(
        address: CartAddressInput!
    ): Cart!
    @field(resolver: "Lunargraphql\\GraphQL\\Resolvers\\CartResolver@setCartShippingAddressMutation")

    """
    Set billing address on the cart
    """
    setCartBillingAddress(
        address: CartAddressInput!
    ): Cart!
    @field(resolver: "Lunargraphql\\GraphQL\\Resolvers\\CartResolver@setCartBillingAddressMutation")

    """
    Apply a coupon code to the cart
    """
    applyCouponToCart(
        coupon: String!
    ): Cart!
    @field(resolver: "Lunargraphql\\GraphQL\\Resolvers\\CartResolver@applyCouponToCartMutation")

    """
    Remove the currently applied coupon from the cart
    """
    removeCouponFromCart: Cart!
    @field(resolver: "Lunargraphql\\GraphQL\\Resolvers\\CartResolver@removeCouponFromCartMutation")

    """
    Select shipping option for the cart
    """
    setCartShippingOption(
        shippingOption: String!
    ): Cart!
    @field(resolver: "Lunargraphql\\GraphQL\\Resolvers\\CartResolver@setCartShippingOptionMutation")

    """
    Force calculate cart totals and taxes
    """
    calculateCart: Cart!
    @field(resolver: "Lunargraphql\\GraphQL\\Resolvers\\CartResolver@calculateCartMutation")
}

input CartAddressInput {
    countryId: ID
    country: String
    title: String
    firstName: String!
    lastName: String!
    companyName: String
    lineOne: String!
    lineTwo: String
    lineThree: String
    city: String!
    state: String
    postcode: String!
    contactEmail: String
    contactPhone: String
    deliveryInstructions: String
    shippingOption: String
}
